#%RAML 1.0
title: Book My Hotels Process API


types:
  BookMyHotel: !include datatypes/BookMyHotelDataType.raml

/hotels:
  get:
    queryParameters:
      city:
        required: false
        type: string
        enum:
          - Bangalore
          - Hyderabad
          - Mumbai
          - Delhi
        default: Bangalore
      hotelGroup:
        type: string
        required: false
        enum:
          - OYO
          - FAB
          - KEYS
          - ALL
        default: ALL
    responses:
      200:
        body:
          application/json:
            example: !include examples/BookMyHotelsExample.raml
            type: BookMyHotel[]